# Generated by Django 2.0.7 on 2018-07-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpslat', models.CharField(blank=True, max_length=10, null=True)),
                ('gpslng', models.CharField(blank=True, max_length=10, null=True)),
                ('trans_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crime_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationCode',
            fields=[
                ('loc_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'location_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('fnd_year', models.CharField(blank=True, max_length=20, null=True)),
                ('sold_date', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_num', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'realestate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealestateIconPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_type', models.IntegerField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'realestate_icon_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Realnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('newspaper_tit', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'realnews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpslat', models.CharField(blank=True, max_length=10, null=True)),
                ('gpslng', models.CharField(blank=True, max_length=10, null=True)),
                ('trans_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmallHouseRealestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('price_deposit', models.CharField(blank=True, max_length=20, null=True)),
                ('price_monthly', models.CharField(blank=True, max_length=20, null=True)),
                ('fnd_year', models.CharField(blank=True, max_length=20, null=True)),
                ('sold_date', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_num', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('area_average', models.CharField(blank=True, max_length=20, null=True)),
                ('buy_type', models.CharField(blank=True, max_length=20, null=True)),
                ('bldg_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'small_house_realestate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmallHouseRealnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('newspaper', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('wr_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'small_house_realnews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransIconPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.IntegerField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'trans_icon_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransInfo',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('gpslat', models.CharField(blank=True, max_length=20, null=True)),
                ('gpslng', models.CharField(blank=True, max_length=20, null=True)),
                ('trans_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trans_info',
                'managed': False,
            },
        ),
    ]
